from . import ClockInRenderer
from . import ClockOutRenderer
from . import ViewHoursRenderer
from . import ViewAverageHoursRenderer
from . import ListRenderer
from . import ViewEmployeesRenderer
from . import EmployeeRenderer
from . import CheckForNewEmployeesRenderer
from . import SetSupervisorRenderer
from . import SetWorkLocationRenderer
from . import SetSubAccountsRenderer
from . import ApproveTimeRenderer
from . import ChangePasswordRenderer
from . import ReportViewer
from . import ReportRenderer
from . import ManageTasks
from . import TaskRenderer
